spring:
  banner:
    location: classpath:banner.txt

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

poll:
  job:
    delay: 10000
    initial-delay: 10000